language: cpp
os: linux
dist: bionic
sudo: required

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install -y --no-install-recommends libedit-dev
  - wget https://apt.llvm.org/llvm.sh
  - chmod +x llvm.sh
  - sudo ./llvm.sh 11
script:
  - ./compile.sh
